generator: Admingenerator\GeneratorBundle\Generator\DoctrineGenerator
params:
  model: Admingenerator\DemoBundle\Entity\Movie
  route_name_prefix: _admindemo
  namespace_prefix: Admingenerator
  bundle_name: DemoBundle
  base_dir: src/Admingenerator
builders:
  ListBuilder:
    params:
      title: Here is a beautifull title no  ???
      display: [ id, title ]
