generator: Admingenerator\GeneratorBundle\Generator\DoctrineGenerator
params:
  model: Admingenerator\DemoBundle\Entity\Movie
  namespace_prefix: Admingenerator
  bundle_name: DemoBundle
builders:
  list:
    params:
      title: Here is a beautifull title no  ???
      display: [ id, title, is_published ]
      max_per_page: 3
      object_actions:
        edit: ~ 
        delete: ~
  edit: 
    params:
      title: You're editing the movie "{{ Movie.title }}"
      display: [ title, is_published ]
  delete: ~ 
